// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1020","screenHeight":"780","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MEGA_skipTextFast","status":true,"description":"fast skip text","parameters":{}},
{"name":"MEGA_CommonEventModules","status":true,"description":"mics common event modules","parameters":{}},
{"name":"MEGA_setFlashAnimation","status":false,"description":"Sets, changes or removes the flashing press indicator.  v1.0","parameters":{"color":"rgba(255, 255, 255, 0.4)","settype":"square","scale":"0.75","data":"X","animate":"on","bouncespeed":"20"}},
{"name":"MEGA_EventChasePlayer","status":true,"description":"v1.07 When a player is in the proximity of a certain event,\nthe event will start chasing or fleeing from the player.","parameters":{"Sight Lock":"300","See Player":"true","Alert Timer":"120","Alert Balloon":"1","Alert Sound":"Attack1","Alert Common Event":"0","Return After":"true","Return Wait":"180"}},
{"name":"YEP_MoveRouteCore","status":true,"description":"v1.02 Expand the number of movement options for the move\nroute events using this plugin.","parameters":{}},
{"name":"FROG_TriggerDistance","status":true,"description":"v1.21 Trigger Events at a distance based on Radius or X/Y Axis","parameters":{}},
{"name":"MEGA_moveToLabel","status":true,"description":"move to eventId","parameters":{}},
{"name":"MEGA_percentMenu","status":true,"description":"percent menu","parameters":{"label":"Era's Courage"}},
{"name":"MrTS_EventNames","status":true,"description":"Allows events to show their names above them.","parameters":{"Default Range":"1","Font Size":"15","Font Name":"GameFont","Fade":"True","Fade Timer":"30"}},
{"name":"GALV_TimedMessagePopups","status":true,"description":"(v.1.7) Display popup message boxes on screen that do not stop gameplay and auto close after a set time.","parameters":{"Y Offset":"-60","Default Windowskin":"Window","Use Arrows":"true","Windowskin Back Opacity":"255","Text Outline Width":"0"}},
{"name":"MEGA_hide_right_click","status":true,"description":"MessageHide Extension. Hide message on right click.","parameters":{}},
{"name":"MEGA_LoadMap","status":true,"description":"","parameters":{}},
{"name":"MEGA_statusMenu","status":true,"description":"status menu","parameters":{"showId":"108","value1":"13","value1_label":"Flayers left: ","value2":"","value2_label":"","value3":"","value3_label":"","value4":"","value4_label":""}},
{"name":"MEGA_gameVersion","status":true,"description":"show game version","parameters":{"version":"0.5.2","x":"20","y":"80","fontSize":"54","position":"left"}},
{"name":"MEGA_ExternalLinks","status":true,"description":"Add link to menu","parameters":{"URL":"https://www.patreon.com/EraHunter","Text":"Patreon","Text2":"Quick Access Room","mapId2":"26"}},
{"name":"MEGA_wasd_movement","status":true,"description":"wasd movement plugin by eruhunterteam","parameters":{}},
{"name":"MEGA_saveMacOs","status":true,"description":"on macos saves in local user dir","parameters":{}},
{"name":"Galv_QuestLog","status":true,"description":"(v.1.3) A system to track quests/sidequests in your RPG.","parameters":{"File":"Quests","Folder":"data","Separator Character":",","- OPTIONS -":"","Font Size":"22","Categories":"Main Quests|#ffcc66,Side Quests|#ffff99","-- ICONS --":"","Not Complete Icon":"163","Complete Icon":"164","Failed Icon":"162","Tracked Quest Icon":"88","-- VOCAB --":"","Quest Command":"Quest Log","Active Cmd Txt":"Active","Completed Cmd Txt":"Complete","Failed Cmd Txt":"Failed","Desc Txt":"Details","Objectives Txt":"Objectives","Difficulty Txt":"","No Tracked Quest":"No Quest Selected","-- EXTRA --":"","Pop XY":"20,20","Pop Time":"130","Pop New Quest":"New Quest:","Pop Complete Quest":"Quest Completed:","Pop Fail Quest":"Quest Failed:","Pop New Objective":"New Objective:","Pop Complete Objective":"Objective Completed:","Pop Fail Objective":"Objective Failed:"}}
];
